# Generated by Django 5.2.16 on 2026-08-06 01:20

import shared.infrastructure.django_fields.correo_field
import shared.infrastructure.django_fields.rut_field
import shared.infrastructure.django_fields.telefono_field
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', shared.infrastructure.django_fields.rut_field.RutField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('correo', shared.infrastructure.django_fields.correo_field.CorreoField(max_length=100, unique=True)),
                ('telefono', shared.infrastructure.django_fields.telefono_field.TelefonoField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'USUARIO',
                'ordering': ['apellido_paterno'],
                'constraints': [models.CheckConstraint(condition=models.Q(('correo__regex', '^([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\\.[A-Za-z]{2,})+$')), name='correo_formato_valido')],
            },
        ),
    ]
