# Generated by Django 5.2.16 on 2026-08-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuario',
            name='correo_formato_valido',
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('correo__regex', '^([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\\.[A-Za-z]{2,})+$')), name='usuario_correo_formato_valido'),
        ),
    ]
